#!/bin/bash

# Env Vars:
# REGISTRY: name of the image registry/namespace to get the images

# Clean up previous run
function clean() {
  set +ex
  echo Cleaning...
  (
  ibmcloud ce app delete -n hello -f
  rm -f out
  ) > /dev/null 2>&1
}

clean
[[ "$1" == "clean" ]] && exit 0

set -ex
## My personal docker hub account
export REGISTRY=${REGISTRY:-docker.io/retgits}

# Create the app
ibmcloud ce app create -n pointscalculator --image ${REGISTRY}/pointscalculator

# Get the URL of the app for later use
URL=$(ibmcloud ce app get -n hello -o url)